# Generated by Django 2.0.3 on 2018-03-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('beginners', models.CharField(max_length=300)),
                ('beginners_last_year', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('name_of_fs', models.CharField(max_length=300)),
                ('type_of_organisation', models.CharField(max_length=300)),
                ('amount_all_students', models.CharField(max_length=300)),
                ('amount_represented_students', models.CharField(max_length=300)),
                ('amount_activ_fachschaftler', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apfifogs.University'),
        ),
    ]
