# Generated by Django 2.0.3 on 2018-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apfifogs', '0002_auto_20180321_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='edit_id',
            field=models.CharField(default='f52bf7f62d1511e8833c0021cccbd64a', max_length=100),
        ),
    ]
