# Generated by Django 2.0.3 on 2018-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apfifogs', '0003_university_edit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='edit_id',
            field=models.CharField(default='bf2df5302d1711e89b0d0021cccbd64a', max_length=100),
        ),
    ]
