# Generated by Django 2.0.3 on 2018-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apfifogs', '0004_auto_20180321_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='edit_id',
            field=models.CharField(default='14daa0aa2d1811e897460021cccbd64a', max_length=100),
        ),
    ]
