# Generated by Django 2.0.3 on 2018-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apfifogs', '0005_auto_20180321_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='edit_id',
            field=models.CharField(default='19f7e0842d1811e8892e0021cccbd64a', max_length=100),
        ),
    ]
