# Generated by Django 2.0.3 on 2018-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apfifogs', '0006_auto_20180321_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='edit_id',
            field=models.CharField(default='67096f942d1a11e899c60021cccbd64a', max_length=100, unique=True),
        ),
    ]
